### ISSUE TITLE
Error: Array to string conversion

### ISSUE THREAD

**Issue by thomasduenser** [alexander-schranz/sulu-form-bundle#5]
If a form contains checkboxes, the form doesn't save any data because the final form data contains arrays. Error message is `Array to string conversion`

**Comment by alexander-schranz** [comment]
this is not a problem of the form bundle itself you need to convert fix your entity for doctrine to save the array as json when you want it, edit your getter and setter functions. I would recommend it to have a subform for multi checkbox.

If its not multiple you probably did accidently use choice instead of checkbox field type.
